name: "Bug Report"
description: "Report a bug"
labels: ["bug"]
body:
 - type: dropdown
   id: priority
   attributes:
      label: "Priority"
      description: "Select the priority of the bug"
      options:
        - "High Priority"
        - "Medium Priority"
        - "Low Priority"

 - type: textarea
   id: description 
   attributes:
      label: "Describe what happened"
      description: "Provide a clear and concise description of the issue."

 - type: textarea
   id: repro-steps
   attributes:
      label: "Repro Case (Steps to Reproduce)"
      description: "Steps to reproduce the behavior."
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error '...'

 - type: textarea
   id: expected-behavior
   attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."

 - type: textarea
   id: screenshots-videos
   attributes:
      label: "Screenshots / Videos (Optional)"
      description: "If applicable, add screenshots or videos to help explain the problem."